# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events for main and preview branch
  push:
    branches: 
    - main 
    - preview 

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains jobs called "Build-Main" and "Build-Preview"
  Build-Main:
    if: ${{ github.ref == 'refs/heads/main' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: clear space
        run: |
          cd /home/ubuntu 
          [ -d DWCDoc ] && rm -rf DWCDoc
          [ -d DocWebCapture-MobileCam-Docs ] && rm -rf DocWebCapture-MobileCam-Docs
          [ -d Docs-Template-Repo-Preview ] && rm -rf Docs-Template-Repo-Preview
          cd /home/ubuntu

      - name: Build the site
        run: |
          cd /home/ubuntu
          [ ! -d DWCDoc ] && mkdir -p DWCDoc
          [ ! -d DocWebCapture-MobileCam-Docs ] && git clone --depth 1 https://github.com/dynamsoft-docs/DocWebCapture-MobileCam-Docs.git DocWebCapture-MobileCam-Docs          
          [ ! -d Docs-Template-Repo-Preview ] && git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Preview
          cp -rfp ./DocWebCapture-MobileCam-Docs/* ./DWCDoc/
          cp -rfp ./Docs-Template-Repo-Preview/* ./DWCDoc/
          cd DWCDoc && bundle exec jekyll build

      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_DYNAMSOFT_LOCAL_SERVER }}
          username: ${{ secrets.FTP_DYNAMSOFT_LOCAL_USER }}
          password: ${{ secrets.FTP_DYNAMSOFT_LOCAL_PASSWORD }}
          port: 21 
          local-dir: /home/ubuntu/DWCDoc/_site/
          server-dir: /www.dynamsoft.com/doc-web-capture/docs/        

  Build-Preview:
    if: ${{ github.ref == 'refs/heads/preview' }}
    # The type of runner that the job will run on
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: clear space
        run: |
          cd /home/ubuntu 
          [ -d DWCDocPreview ] && rm -rf DWCDocPreview
          [ -d DocWebCapture-MobileCam-Docs-preview ] && rm -rf DocWebCapture-MobileCam-Docs-preview
          [ -d Docs-Template-Repo-Preview ] && rm -rf Docs-Template-Repo-Preview
          cd /home/ubuntu

      - name: Build the site
        run: |
          cd /home/ubuntu
          [ ! -d DWCDocPreview ] && mkdir -p DWCDocPreview
          [ ! -d DocWebCapture-MobileCam-Docs-preview ] && git clone --depth 1 --branch preview https://${{ secrets.GIT_USER }}:${{ secrets.GIT_PAT }}@github.com/dynamsoft-docs/DocWebCapture-MobileCam-Docs.git DocWebCapture-MobileCam-Docs-preview          
          [ ! -d Docs-Template-Repo-Preview ] && git clone --depth 1 --branch preview https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Preview
          cp -rfp ./DocWebCapture-MobileCam-Docs-preview/* ./DWCDocPreview/
          cp -rfp ./Docs-Template-Repo-Preview/* ./DWCDocPreview/
          sed -i -e "1,3s/blob\/master$/blob\/preview/" \
          -e "1,3s/blob\/main$/blob\/preview/" /home/ubuntu/DWCDocPreview/_config.yml
          cd DWCDocPreview && bundle exec jekyll build
         



      - name: Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_TEST_SITE_SERVER }}
          username: ${{ secrets.FTP_TEST_SITE_USER }}
          password: ${{ secrets.FTP_TEST_SITE_PASSWORD }}
          port: 7500 
          local-dir: /home/ubuntu/DWCDocPreview/_site/
          server-dir: /www.dynamsoft.com/doc-web-capture/docs/

          
